### ISSUE TITLE
"open_basedir restriction in effect" error

### ISSUE THREAD

**Issue by Daaaaad** [vint3creative/shortcodes-for-woocommerce#4]
Hello,

When "shortcodes-for-woocommerce" is enable I get this PHP error in my logs:

PHP Warning:  require_once(): open_basedir restriction in effect in woo-framework-shortcodes/functions/js/shortcode-generator/js/dialog-js.php on line 12

Can you help?

**Comment by s3rgiosan** [comment]
Hi @Daaaaad,

That warning is related to [Woo Framework Shortcodes](https://wordpress.org/plugins/woo-framework-shortcodes/) and not with this plugin.

Regards
